msg = input('Digite algo:')
print("{} está em lestras maiusculas?".format(msg), msg.isupper())
print("{} está em letras minusculas?".format(msg), msg.islower())
print("{} é um numeroex113?".format(msg), msg.isnumeric())
print("{} é uma letra?".format(msg), msg.isalpha())
print("{} é um espaco?".format(msg), msg.isspace())
print("{} é um numeroex113 decimal?".format(msg), msg.isdecimal())
print("{} é um identificador?".format(msg), msg.isidentifier())
print("{} é um printable?".format(msg), msg.isprintable())
print('Esse valor é do tipo primitivo', type(msg))
print('{} é alfanumerico?'.format(msg), msg.isalnum())
print('{} está capitalizada?'.format(msg), msg.istitle())